name: el-rpm

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  rpm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jw3/mock-srpm@fetch
        with:
          chroot: rocky+epel-8-x86_64
          spec: mobilitydb.spec
          fetch-sources: true
          cache: true
      - uses: jw3/mock-rpm@v1
        with:
          chroot: rocky+epel-8-x86_64
          srpm: mobilitydb-*.src.rpm
          cache: true
          debug: true
